// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftOMator.Infrastructure;

#nullable disable

namespace ShiftOMator.Infrastructure.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20260820030750_PersonEmployeeIdUniqueIndex")]
    partial class PersonEmployeeIdUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocationPlanningUnit", b =>
                {
                    b.Property<string>("LocationsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlanningUnitId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LocationsId", "PlanningUnitId");

                    b.HasIndex("PlanningUnitId");

                    b.ToTable("LocationPlanningUnit");
                });

            modelBuilder.Entity("ShiftOMator.Domain.Absence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("ImportBatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastSeenInImportAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SyncedToHrAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("ShiftOMator.Domain.AbsenceCapacityRule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CountsCompDays")
                        .HasColumnType("bit");

                    b.Property<string>("CountsTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationBucket")
                        .HasColumnType("int");

                    b.Property<int>("LongThresholdWorkdays")
                        .HasColumnType("int");

                    b.Property<int>("MaxConcurrent")
                        .HasColumnType("int");

                    b.Property<int>("ScopeKind")
                        .HasColumnType("int");

                    b.Property<string>("ScopeShiftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("AbsenceCapacityRules");
                });

            modelBuilder.Entity("ShiftOMator.Domain.Acknowledgement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ByPersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IssueKey")
                        .IsUnique();

                    b.ToTable("Acknowledgements");
                });

            modelBuilder.Entity("ShiftOMator.Domain.Assignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ContentKind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit");

                    b.Property<int?>("Marker")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShiftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Date")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("ShiftOMator.Domain.AssignmentHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssignmentHistory");
                });

            modelBuilder.Entity("ShiftOMator.Domain.CompDayEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("ActualDate")
                        .HasColumnType("date");

                    b.Property<string>("EarnedForAssignmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EarnedForDate")
                        .HasColumnType("date");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ProposedDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SyncedToHrAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompDayEntries");
                });

            modelBuilder.Entity("ShiftOMator.Domain.DayConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Weekdays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("DayConfigurations");
                });

            modelBuilder.Entity("ShiftOMator.Domain.DraftChange", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DraftSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Op")
                        .HasColumnType("int");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DraftSessionId");

                    b.ToTable("DraftChanges");
                });

            modelBuilder.Entity("ShiftOMator.Domain.DraftSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EditorPersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RangeFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RangeTo")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("DraftSessions");
                });

            modelBuilder.Entity("ShiftOMator.Domain.Holiday", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("bit");

                    b.Property<string>("LocationIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("ShiftOMator.Domain.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayCalendarKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekendDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ShiftOMator.Domain.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvailableWeekdays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalendarToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultShiftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrgCategory")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WeekendEligible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ShiftOMator.Domain.PlanningUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GroupBy")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LocationIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanningUnits");
                });

            modelBuilder.Entity("ShiftOMator.Domain.Shift", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CountsAsCoverage")
                        .HasColumnType("bit");

                    b.Property<bool>("CrossesMidnight")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EditableTime")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time");

                    b.Property<string>("Hotkey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ShiftOMator.Domain.ShiftEligibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxPerWeek")
                        .HasColumnType("int");

                    b.Property<int?>("MinPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShiftId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TargetShare")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ShiftEligibilities");
                });

            modelBuilder.Entity("ShiftOMator.Domain.ShiftRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayConfigurationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("Max")
                        .HasColumnType("int");

                    b.Property<int>("Min")
                        .HasColumnType("int");

                    b.Property<string>("ShiftId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TimingOverrideCrossesMidnight")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("TimingOverrideEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("TimingOverrideStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DayConfigurationId");

                    b.ToTable("ShiftRequirements");
                });

            modelBuilder.Entity("LocationPlanningUnit", b =>
                {
                    b.HasOne("ShiftOMator.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftOMator.Domain.PlanningUnit", null)
                        .WithMany()
                        .HasForeignKey("PlanningUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftOMator.Domain.AbsenceCapacityRule", b =>
                {
                    b.HasOne("ShiftOMator.Domain.PlanningUnit", null)
                        .WithMany("AbsenceCapacityRules")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftOMator.Domain.Assignment", b =>
                {
                    b.OwnsOne("ShiftOMator.Domain.TimeOverride", "TimeOverride", b1 =>
                        {
                            b1.Property<string>("AssignmentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("CrossesMidnight")
                                .HasColumnType("bit");

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time");

                            b1.HasKey("AssignmentId");

                            b1.ToTable("Assignments");

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId");
                        });

                    b.Navigation("TimeOverride");
                });

            modelBuilder.Entity("ShiftOMator.Domain.DayConfiguration", b =>
                {
                    b.HasOne("ShiftOMator.Domain.PlanningUnit", null)
                        .WithMany("DayConfigurations")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftOMator.Domain.DraftChange", b =>
                {
                    b.HasOne("ShiftOMator.Domain.DraftSession", null)
                        .WithMany("Changes")
                        .HasForeignKey("DraftSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftOMator.Domain.Person", b =>
                {
                    b.OwnsOne("ShiftOMator.Domain.PersonConstraints", "Constraints", b1 =>
                        {
                            b1.Property<string>("PersonId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("MaxConsecutiveDays")
                                .HasColumnType("int");

                            b1.Property<int?>("MaxWeekendsPerQuarter")
                                .HasColumnType("int");

                            b1.Property<int>("MinRestHours")
                                .HasColumnType("int");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("ShiftOMator.Domain.PersonPreferences", "Preferences", b1 =>
                        {
                            b1.Property<string>("PersonId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("AvoidsWeekdays")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BlackoutDates")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Note")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PreferredPartnerIds")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Constraints")
                        .IsRequired();

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("ShiftOMator.Domain.PlanningUnit", b =>
                {
                    b.OwnsOne("ShiftOMator.Domain.CompOffPolicy", "CompOffPolicy", b1 =>
                        {
                            b1.Property<string>("PlanningUnitId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("AgingThresholdDays")
                                .HasColumnType("int");

                            b1.Property<string>("ExcludedWeekdays")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("RequiresApprovalWhenNoSlot")
                                .HasColumnType("bit");

                            b1.Property<int>("WindowAfterDays")
                                .HasColumnType("int");

                            b1.Property<int>("WindowBeforeDays")
                                .HasColumnType("int");

                            b1.HasKey("PlanningUnitId");

                            b1.ToTable("PlanningUnits");

                            b1.WithOwner()
                                .HasForeignKey("PlanningUnitId");
                        });

                    b.Navigation("CompOffPolicy")
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftOMator.Domain.Shift", b =>
                {
                    b.HasOne("ShiftOMator.Domain.PlanningUnit", null)
                        .WithMany("Shifts")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftOMator.Domain.ShiftEligibility", b =>
                {
                    b.HasOne("ShiftOMator.Domain.Person", null)
                        .WithMany("Eligibility")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftOMator.Domain.ShiftRequirement", b =>
                {
                    b.HasOne("ShiftOMator.Domain.DayConfiguration", null)
                        .WithMany("ShiftRequirements")
                        .HasForeignKey("DayConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftOMator.Domain.DayConfiguration", b =>
                {
                    b.Navigation("ShiftRequirements");
                });

            modelBuilder.Entity("ShiftOMator.Domain.DraftSession", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("ShiftOMator.Domain.Person", b =>
                {
                    b.Navigation("Eligibility");
                });

            modelBuilder.Entity("ShiftOMator.Domain.PlanningUnit", b =>
                {
                    b.Navigation("AbsenceCapacityRules");

                    b.Navigation("DayConfigurations");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
