{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shift-o-mator
  labels:
    {{- include "shift-o-mator.labels" . | nindent 4 }}
  annotations:
    appgw.ingress.kubernetes.io/backend-protocol: http
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: shift-o-mator-api
                port: { number: 80 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shift-o-mator-web
                port: { number: 80 }
{{- end }}
