/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetReference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListDrafts"];
        put?: never;
        post: operations["OpenDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListDraftChanges"];
        put?: never;
        post: operations["AppendDraftChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{id}/changes/{changeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RemoveDraftChange"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DiscardDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublishDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Suggest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auto-populate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AutoPopulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acknowledgements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdatePerson"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LocationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LocationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/holidays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Holiday"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HolidayRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Holiday"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/holidays/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HolidayRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Holiday"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanningUnit"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UnitRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanningUnit"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UnitRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanningUnit"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/absence-capacity-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AbsenceCapacityRule"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AbsenceCapacityRuleRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AbsenceCapacityRule"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/absence-capacity-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AbsenceCapacityRuleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AbsenceCapacityRule"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shift"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShiftRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shift"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/shifts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shift"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShiftRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shift"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/day-configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DayConfiguration"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DayConfigurationNewVersionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DayConfiguration"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/day-configurations/{id}/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DayConfigurationLabelRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DayConfiguration"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/day-configurations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Person"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminPersonRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Person"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminPersonRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Person"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Absence: {
            id: string;
            personId: string;
            type?: components["schemas"]["AbsenceType"];
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            source?: components["schemas"]["AbsenceSource"];
            importBatchId?: null | string;
            /** Format: date-time */
            lastSeenInImportAt?: null | string;
            /** Format: date-time */
            syncedToHrAt?: null | string;
            note?: null | string;
        };
        AbsenceCapacityRule: {
            id: string;
            unitId: string;
            scopeKind?: components["schemas"]["AbsenceCapacityScopeKind"];
            scopeShiftId?: null | string;
            durationBucket?: components["schemas"]["AbsenceDurationBucket"];
            /** Format: int32 */
            longThresholdWorkdays?: number | string;
            /** Format: int32 */
            maxConcurrent?: number | string;
            countsTypes?: components["schemas"]["AbsenceType"][];
            countsCompDays?: boolean;
        };
        AbsenceCapacityRuleRequest: {
            unitId: string;
            scopeKind: components["schemas"]["AbsenceCapacityScopeKind"];
            scopeShiftId: null | string;
            durationBucket: components["schemas"]["AbsenceDurationBucket"];
            /** Format: int32 */
            longThresholdWorkdays: number | string;
            /** Format: int32 */
            maxConcurrent: number | string;
            countsTypes: components["schemas"]["AbsenceType"][];
            countsCompDays: boolean;
        };
        /** @enum {unknown} */
        AbsenceCapacityScopeKind: "unit" | "shiftPool";
        /** @enum {unknown} */
        AbsenceDurationBucket: "short" | "long";
        /** @enum {unknown} */
        AbsenceSource: "import" | "manual";
        /** @enum {unknown} */
        AbsenceType: "vacation" | "sick" | "other";
        Acknowledgement: {
            /** Format: int32 */
            id?: number | string;
            issueKey: string;
            comment: string;
            byPersonId: string;
            /** Format: date-time */
            at: string;
        };
        AcknowledgeRequest: {
            issueKey: string;
            comment: string;
            byPersonId: string;
        };
        AdminPersonRequest: {
            displayName: string;
            initials: string;
            employeeId: null | string;
            unitId: string;
            locationId: string;
            orgCategory: components["schemas"]["OrgCategory"];
            isActive: boolean;
            isIncluded: boolean;
        };
        AppendChangeRequest: {
            targetType: components["schemas"]["DraftTargetType"];
            op: components["schemas"]["DraftOp"];
            entityId: string;
            after: null | components["schemas"]["JsonElement"];
        };
        Assignment: {
            id: string;
            personId: string;
            /** Format: date */
            date: string;
            unitId: string;
            contentKind?: components["schemas"]["AssignmentContentKind"];
            shiftId?: null | string;
            timeOverride?: null | components["schemas"]["TimeOverride"];
            marker?: null | components["schemas"]["RosterMarker"];
            isWeekend?: boolean;
            note?: null | string;
            source?: components["schemas"]["AssignmentSource"];
            /** Format: int32 */
            version?: number | string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            updatedBy?: null | string;
            /** Format: date-time */
            updatedAt?: null | string;
        };
        /** @enum {unknown} */
        AssignmentContentKind: "shift" | "marker";
        AssignmentHistoryEntry: {
            id: string;
            assignmentId: string;
            action?: components["schemas"]["HistoryAction"];
            snapshotJson?: null | string;
            actorId: string;
            /** Format: date-time */
            at: string;
        };
        /** @enum {unknown} */
        AssignmentSource: "manual" | "generated" | "imported";
        AutoPopulateRequest: {
            unitId: string;
            /** Format: date */
            rangeFrom: string;
            /** Format: date */
            rangeTo: string;
            lockedAssignmentIds: null | string[];
            actorId: string;
        };
        Candidate: {
            personId: string;
            name: string;
            /** Format: int32 */
            shiftCountLast90: number | string;
            /** Format: int32 */
            daysSinceLastHeld: null | number | string;
            /** Format: int32 */
            weekendLoad: number | string;
            warnings: string[];
        };
        CandidateResult: {
            available: components["schemas"]["Candidate"][];
            excluded: components["schemas"]["ExcludedCandidate"][];
            /** Format: double */
            teamWeekendAverage: number | string;
        };
        CompDayEntry: {
            id: string;
            personId: string;
            earnedForAssignmentId: string;
            /** Format: date */
            earnedForDate: string;
            trigger?: components["schemas"]["CompDayTrigger"];
            /** Format: date */
            proposedDate?: null | string;
            /** Format: date */
            actualDate?: null | string;
            status?: components["schemas"]["CompDayStatus"];
            /** Format: date-time */
            syncedToHrAt?: null | string;
        };
        /** @enum {unknown} */
        CompDayStatus: "proposed" | "scheduled" | "taken" | "declined" | "pendingApproval";
        /** @enum {unknown} */
        CompDayTrigger: "saturday" | "sunday" | "holiday";
        CompOffPolicy: {
            /** Format: int32 */
            windowBeforeDays?: number | string;
            /** Format: int32 */
            windowAfterDays?: number | string;
            excludedWeekdays?: components["schemas"]["IsoWeekday"][];
            /** Format: int32 */
            agingThresholdDays?: number | string;
            requiresApprovalWhenNoSlot?: boolean;
        };
        CompOffPolicyRequest: {
            /** Format: int32 */
            windowBeforeDays: number | string;
            /** Format: int32 */
            windowAfterDays: number | string;
            excludedWeekdays: components["schemas"]["IsoWeekday"][];
            /** Format: int32 */
            agingThresholdDays: number | string;
            requiresApprovalWhenNoSlot: boolean;
        };
        CoverageCell: {
            /** Format: date */
            date: string;
            unitId: string;
            shiftId: string;
            /** Format: int32 */
            actual?: number | string;
            /** Format: int32 */
            min?: number | string;
            /** Format: int32 */
            max?: null | number | string;
            level?: components["schemas"]["CoverageLevel"];
            appliedKey?: components["schemas"]["DayConfigKey"];
            ruleLabel?: null | string;
        };
        /** @enum {unknown} */
        CoverageLevel: "gap" | "thin" | "ok" | "over";
        /** @enum {unknown} */
        DayConfigKey: "weekday" | "friday" | "weekend" | "holiday" | "date";
        DayConfiguration: {
            id: string;
            unitId: string;
            key?: components["schemas"]["DayConfigKey"];
            weekdays?: components["schemas"]["IsoWeekday"][];
            /** Format: date */
            date?: null | string;
            label?: null | string;
            /** Format: date */
            effectiveFrom: string;
            shiftRequirements?: components["schemas"]["ShiftRequirement"][];
        };
        DayConfigurationLabelRequest: {
            label: null | string;
        };
        DayConfigurationNewVersionRequest: {
            unitId: string;
            key: components["schemas"]["DayConfigKey"];
            weekdays: components["schemas"]["IsoWeekday"][];
            /** Format: date */
            date: null | string;
            label: null | string;
            /** Format: date */
            effectiveFrom: string;
            shiftRequirements: components["schemas"]["ShiftRequirementRequest"][];
        };
        DayConfigurationSummary: {
            /** Format: date */
            date: string;
            unitId: string;
            dayConfigurationId: string;
            key: components["schemas"]["DayConfigKey"];
            label: null | string;
        };
        DraftChange: {
            id: string;
            draftSessionId: string;
            /** Format: int32 */
            seq?: number | string;
            /** Format: date-time */
            at: string;
            targetType?: components["schemas"]["DraftTargetType"];
            op?: components["schemas"]["DraftOp"];
            beforeJson?: null | string;
            afterJson?: null | string;
        };
        DraftNotFoundResponse: {
            code: string;
            draftId: string;
        };
        /** @enum {unknown} */
        DraftOp: "create" | "update" | "delete";
        DraftSession: {
            id: string;
            editorPersonId: string;
            unitId: string;
            /** Format: date */
            rangeFrom: string;
            /** Format: date */
            rangeTo: string;
            status?: components["schemas"]["DraftStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            changes?: components["schemas"]["DraftChange"][];
        };
        /** @enum {unknown} */
        DraftStatus: "open" | "published" | "discarded";
        /** @enum {unknown} */
        DraftTargetType: "assignment" | "absence" | "compDay";
        ErrorResponse: {
            code: string;
            message: string;
        };
        ExcludedCandidate: {
            personId: string;
            name: string;
            reason: string;
        };
        Gap: {
            /** Format: date */
            date: string;
            shiftId: string;
            code: string;
            reason: string;
        };
        /** @enum {unknown} */
        GroupBy: "location" | "region" | "orgCategory";
        /** @enum {unknown} */
        HistoryAction: "created" | "updated" | "deleted";
        Holiday: {
            id: string;
            /** Format: date */
            date: string;
            name: string;
            locationIds?: string[];
            isFullDay?: boolean;
        };
        HolidayRequest: {
            /** Format: date */
            date: string;
            name: string;
            locationIds: string[];
            isFullDay: boolean;
        };
        InvalidRangeResponse: {
            code: string;
            message: string;
        };
        /** @enum {unknown} */
        IsoWeekday: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
        Issue: {
            key: string;
            level?: components["schemas"]["IssueLevel"];
            category?: components["schemas"]["IssueCategory"];
            code?: components["schemas"]["IssueCode"];
            message: string;
            unitId: string;
            /** Format: date */
            date?: null | string;
            personId?: null | string;
            shiftId?: null | string;
        };
        /** @enum {unknown} */
        IssueCategory: "gap" | "conflict" | "fairness" | "policy";
        /** @enum {unknown} */
        IssueCode: "coverageGap" | "coverageThin" | "coverageOverMax" | "assignedDuringAbsence" | "assignedDuringCompDay" | "doubleAssignment" | "shiftNotEligible" | "shiftOutsideRegion" | "shiftNotInDayConfig" | "absenceCapacityExceeded" | "minRestViolated" | "consecutiveDaysExceeded" | "weekendLoadExceeded" | "unavailableWeekday" | "preferenceViolated" | "targetShareDeviation" | "compDayAging" | "compDayPendingApproval";
        /** @enum {unknown} */
        IssueLevel: "blocking" | "warning" | "info";
        JsonElement: unknown;
        Location: {
            id: string;
            name: string;
            country: string;
            timeZone: string;
            holidayCalendarKey: string;
            weekendDays?: components["schemas"]["IsoWeekday"][];
        };
        LocationRequest: {
            name: string;
            country: string;
            timeZone: string;
            holidayCalendarKey: string;
            weekendDays: components["schemas"]["IsoWeekday"][];
        };
        MeResponse: {
            personId: null | string;
            displayName: null | string;
            role: null | string;
        };
        NotFoundResponse: {
            code: string;
            id: string;
        };
        OpenDraftRequest: {
            editorPersonId: string;
            unitId: string;
            /** Format: date */
            rangeFrom: string;
            /** Format: date */
            rangeTo: string;
        };
        /** @enum {unknown} */
        OrgCategory: "support" | "serviceTransition" | "management";
        Person: {
            id: string;
            displayName: string;
            initials: string;
            employeeId?: null | string;
            unitId: string;
            locationId: string;
            orgCategory?: components["schemas"]["OrgCategory"];
            isActive?: boolean;
            isIncluded?: boolean;
            availableWeekdays?: components["schemas"]["IsoWeekday"][];
            defaultShiftId?: null | string;
            weekendEligible?: boolean;
            constraints?: components["schemas"]["PersonConstraints"];
            preferences?: null | components["schemas"]["PersonPreferences"];
            calendarToken: string;
            eligibility?: components["schemas"]["ShiftEligibility"][];
        };
        PersonConstraints: {
            /** Format: int32 */
            minRestHours?: number | string;
            /** Format: int32 */
            maxConsecutiveDays?: number | string;
            /** Format: int32 */
            maxWeekendsPerQuarter?: null | number | string;
        };
        PersonPreferences: {
            avoidsWeekdays?: components["schemas"]["IsoWeekday"][];
            preferredPartnerIds?: string[];
            blackoutDates?: string[];
            note?: null | string;
        };
        PersonPreferencesRequest: {
            avoidsWeekdays: null | components["schemas"]["IsoWeekday"][];
            preferredPartnerIds: null | string[];
            blackoutDates: null | string[];
            note: null | string;
        };
        PlanningUnit: {
            id: string;
            name: string;
            kind?: components["schemas"]["UnitKind"];
            groupBy?: components["schemas"]["GroupBy"];
            primaryLocationId: string;
            locationIds?: string[];
            compOffPolicy?: components["schemas"]["CompOffPolicy"];
            locations?: components["schemas"]["Location"][];
            shifts?: components["schemas"]["Shift"][];
            dayConfigurations?: components["schemas"]["DayConfiguration"][];
            absenceCapacityRules?: components["schemas"]["AbsenceCapacityRule"][];
        };
        PublishDraftResponse: {
            /** Format: int32 */
            remainingGaps: number | string;
            history: components["schemas"]["AssignmentHistoryEntry"][];
            generatedCompDays: components["schemas"]["CompDayEntry"][];
        };
        ReferenceResponse: {
            locations: components["schemas"]["Location"][];
            holidays: components["schemas"]["Holiday"][];
            units: components["schemas"]["PlanningUnit"][];
            shifts: components["schemas"]["Shift"][];
            dayConfigurations: components["schemas"]["DayConfiguration"][];
            people: components["schemas"]["Person"][];
            absenceCapacityRules: components["schemas"]["AbsenceCapacityRule"][];
        };
        Result: {
            assignments: components["schemas"]["Assignment"][];
            compDays: components["schemas"]["CompDayEntry"][];
            gaps: components["schemas"]["Gap"][];
            /** Format: int32 */
            assignedCount?: number | string;
        };
        /** @enum {unknown} */
        RosterMarker: "off" | "notScheduled" | null;
        SchedulePlan: {
            assignments: components["schemas"]["Assignment"][];
            absences: components["schemas"]["Absence"][];
            compDays: components["schemas"]["CompDayEntry"][];
        };
        ScheduleResponse: {
            unitIds: string[];
            plan: components["schemas"]["SchedulePlan"];
            coverage: components["schemas"]["CoverageCell"][];
            issues: components["schemas"]["Issue"][];
            acknowledgedIssueKeys: string[];
            dayConfigurations: components["schemas"]["DayConfigurationSummary"][];
            overlaidDraftId: null | string;
        };
        Shift: {
            id: string;
            unitId: string;
            code: string;
            label: string;
            description?: null | string;
            color: string;
            hotkey?: null | string;
            timeZone: string;
            /** Format: time */
            start?: string;
            /** Format: time */
            end?: string;
            crossesMidnight?: boolean;
            /** Format: int32 */
            breakMinutes?: number | string;
            countsAsCoverage?: boolean;
            editableTime?: boolean;
        };
        ShiftEligibility: {
            /** Format: int32 */
            id?: number | string;
            personId: string;
            shiftId: string;
            /** Format: double */
            targetShare?: number | string;
            /** Format: int32 */
            minPerWeek?: null | number | string;
            /** Format: int32 */
            maxPerWeek?: null | number | string;
        };
        ShiftEligibilityRequest: {
            shiftId: string;
            /** Format: double */
            targetShare: number | string;
            /** Format: int32 */
            minPerWeek: null | number | string;
            /** Format: int32 */
            maxPerWeek: null | number | string;
        };
        ShiftRequest: {
            unitId: string;
            code: string;
            label: string;
            description: null | string;
            color: string;
            hotkey: null | string;
            timeZone: string;
            /** Format: time */
            start: string;
            /** Format: time */
            end: string;
            crossesMidnight: boolean;
            /** Format: int32 */
            breakMinutes: number | string;
            countsAsCoverage: boolean;
            editableTime: boolean;
        };
        ShiftRequirement: {
            /** Format: int32 */
            id?: number | string;
            dayConfigurationId: string;
            shiftId: string;
            /** Format: int32 */
            min?: number | string;
            /** Format: int32 */
            max?: null | number | string;
            isDefault?: boolean;
            /** Format: time */
            timingOverrideStart?: null | string;
            /** Format: time */
            timingOverrideEnd?: null | string;
            timingOverrideCrossesMidnight?: null | boolean;
        };
        ShiftRequirementRequest: {
            shiftId: string;
            /** Format: int32 */
            min: number | string;
            /** Format: int32 */
            max: null | number | string;
            isDefault: boolean;
            /** Format: time */
            timingOverrideStart: null | string;
            /** Format: time */
            timingOverrideEnd: null | string;
            timingOverrideCrossesMidnight: null | boolean;
        };
        SuggestRequest: {
            shiftId: string;
            /** Format: date */
            date: string;
            unitId: string;
            excludePersonIds: null | string[];
        };
        TimeOverride: {
            /** Format: time */
            start?: string;
            /** Format: time */
            end?: string;
            crossesMidnight?: boolean;
        };
        /** @enum {unknown} */
        UnitKind: "region" | "crossRegion";
        UnitRequest: {
            name: string;
            kind: components["schemas"]["UnitKind"];
            groupBy: components["schemas"]["GroupBy"];
            primaryLocationId: string;
            locationIds: string[];
            compOffPolicy: components["schemas"]["CompOffPolicyRequest"];
        };
        UpdatePersonRequest: {
            eligibility: components["schemas"]["ShiftEligibilityRequest"][];
            availableWeekdays: components["schemas"]["IsoWeekday"][];
            defaultShiftId: null | string;
            weekendEligible: boolean;
            preferences: null | components["schemas"]["PersonPreferencesRequest"];
        };
        ValidationErrorResponse: {
            errors: {
                [key: string]: string[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetReference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceResponse"];
                };
            };
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    GetSchedule: {
        parameters: {
            query: {
                unitId: string;
                from: string;
                to: string;
                draftId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRangeResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftNotFoundResponse"];
                };
            };
        };
    };
    ListDrafts: {
        parameters: {
            query?: {
                unitId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSession"][];
                };
            };
        };
    };
    OpenDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenDraftRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSession"];
                };
            };
        };
    };
    ListDraftChanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftChange"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppendDraftChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendChangeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftChange"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RemoveDraftChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                changeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DiscardDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSession"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublishDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishDraftResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Suggest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateResult"];
                };
            };
        };
    };
    AutoPopulate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoPopulateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Acknowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acknowledgement"];
                };
            };
        };
    };
    GetHistory: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentHistoryEntry"][];
                };
            };
        };
    };
    UpdatePerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePersonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
}
